    SUPABASE_URL = "https://rdchqslemzagbadegfcp.supabase.co"
    SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkY2hxc2xlbXphZ2JhZGVnZmNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTEzOTgsImV4cCI6MjA3MTM4NzM5OH0.y0cTowsVOFCuSoCHYm6d3QxgBXQ4mcGyhV90OvrVzOI"


