    SUPABASE_URL = "https://rdchqslemzagbadegfcp.supabase.co"
    SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkY2hxc2xlbXphZ2JhZGVnZmNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTEzOTgsImV4cCI6MjA3MTM4NzM5OH0.y0cTowsVOFCuSoCHYm6d3QxgBXQ4mcGyhV90OvrVzOI"


# SMTP (usa TLS por 587; es lo que espera tu código)
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = "587"
EMAIL_USER = "wormsgantt@gmail.com"
EMAIL_PASSWORD = "Mosaico88"
EMAIL_FROM = "Gantt Worms <wormsgantt@gmail.com>"